apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false #datasource not default
    editable: false #not editable on grafana website
    version: 1
    uid: loki

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3100
    isDefault: true
    editable: false #not editable on grafana website
    version: 1
    uid: tempo